import { useEffect, useState } from 'react';
import { ApiError, type ReconciliationChallenge, type ReconciliationPlan, type ResearchApi } from './api';

export function ReconciliationPanel({ api, sessionId }: { api: ResearchApi; sessionId: string }) {
  const [plan, setPlan] = useState<ReconciliationPlan>(); const [pin, setPin] = useState(''); const [challenge, setChallenge] = useState<ReconciliationChallenge>(); const [phrase, setPhrase] = useState(''); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false);
  const supported = Boolean(api.reconciliation && api.createReconciliationChallenge && api.executeReconciliation);
  const clearDecision = () => { setPin(''); setChallenge(undefined); setPhrase(''); };
  const load = async () => { if (!api.reconciliation) return; setBusy(true); try { const next = await api.reconciliation(sessionId); if (plan && next.planSha256 !== plan.planSha256) clearDecision(); setPlan(next); setStatus(next.complete ? 'Đối soát đã hoàn tất.' : 'Đã tải trạng thái đối soát mới nhất.'); } catch (error) { if (error instanceof ApiError && error.status === 401) clearDecision(); setStatus('Không thể tải trạng thái đối soát.'); } finally { setBusy(false); } };
  useEffect(() => { let active = true; void Promise.resolve().then(async () => { clearDecision(); if (!api.reconciliation) return; const next = await api.reconciliation(sessionId); if (active) { setPlan(next); setStatus(next.complete ? 'Đối soát đã hoàn tất.' : 'Đã tải trạng thái đối soát mới nhất.'); } }).catch(() => { if (active) setStatus('Không thể tải trạng thái đối soát.'); }); return () => { active = false; }; }, [api, sessionId]);
  const issue = async () => { if (!api.createReconciliationChallenge || !pin) return; setBusy(true); try { const issued = await api.createReconciliationChallenge(sessionId, pin, 'EXECUTE_LOCAL_RECONCILIATION'); setChallenge(issued); setPhrase(''); setPin(''); setStatus('Đã xác thực lại. Hãy nhập đúng cụm xác nhận được hiển thị.'); } catch { clearDecision(); setStatus('Không thể tạo xác nhận: PIN, kế hoạch hoặc quyền hiện tại không hợp lệ.'); } finally { setBusy(false); } };
  const execute = async () => { if (!api.executeReconciliation || !challenge) return; setBusy(true); try { await api.executeReconciliation(sessionId, challenge.challengeToken, phrase); clearDecision(); await load(); } catch (error) { clearDecision(); setStatus(error instanceof ApiError && error.code === 'AUTHORITY_NOT_ISSUED' ? 'Chưa có thẩm quyền thực thi xóa dữ liệu thật.' : 'Xác nhận đã hết hạn, thay đổi hoặc bị từ chối.'); } finally { setBusy(false); } };
  if (!supported) return null;
  return <section className="reconciliationPanel" aria-labelledby="reconciliation-heading"><h4 id="reconciliation-heading">Đối soát sau khi rút khỏi nghiên cứu</h4><p className="technicalNote">Rút khỏi nghiên cứu đã được ghi nhận. Xóa trên máy và xác nhận bản sao bên ngoài là hai căn cứ riêng.</p><button className="quietButton" disabled={busy} onClick={() => void load()}>Tải lại đối soát</button><p role="status" aria-live="polite">{status}</p>{plan && <><dl className="reconciliationCounts"><div><dt>Tệp cục bộ</dt><dd>{plan.localTargetTotal}</dd></div><div><dt>Bản sao bên ngoài</dt><dd>{plan.externalTargetTotal}</dd></div><div><dt>Bị chặn</dt><dd>{plan.blockedTargetTotal}</dd></div><div><dt>Cần khôi phục</dt><dd>{plan.recoveryRequiredTotal}</dd></div></dl><p>Người tham gia: {plan.participantPseudonym}</p>{plan.blockerCodes.length > 0 && <ul>{plan.blockerCodes.map((code) => <li key={code}>{code}</li>)}</ul>}{!plan.complete && plan.localTargetTotal > 0 && !challenge && <><label htmlFor="reconciliation-pin">Nhập lại PIN người đánh giá</label><input id="reconciliation-pin" type="password" value={pin} autoComplete="off" onChange={(event) => setPin(event.target.value)} /><button className="orangeButton" disabled={busy || !pin} onClick={() => void issue()}>Tạo xác nhận xóa cục bộ</button></>}{challenge && <><p>Nhập chính xác: <strong>{challenge.confirmationPhrase}</strong></p><label htmlFor="reconciliation-phrase">Cụm xác nhận</label><input id="reconciliation-phrase" value={phrase} autoComplete="off" onChange={(event) => setPhrase(event.target.value)} /><button className="orangeButton" disabled={busy || phrase !== challenge.confirmationPhrase} onClick={() => void execute()}>Thực thi đối soát cục bộ</button><button className="quietButton" onClick={clearDecision}>Hủy xác nhận</button></>}{plan.externalTargetTotal > 0 && <p className="researchStatusBanner">Bản sao bên ngoài vẫn cần quy trình thể chế và xác nhận riêng; ứng dụng không kết nối tài khoản bên ngoài.</p>}</>}</section>;
}
