import { useEffect, useRef, useState } from 'react';
import { ApiError, isMissingResearchRoute, isSyntheticReviewApi, newIdempotencyKey } from './api';
import type { ResearchApi, ResearchParticipant, ResearchReadiness, ResearchRecovery, ResearchSession, ResearchStudy, WithdrawalStatus } from './api';
import { ReconciliationPanel } from './ReconciliationPanel';
import { SyntheticValidationPanel } from './SyntheticValidationPanel';
import { formatRetentionEndDate, parseRetentionEndDate } from './retention';
import './research.css';

const gates: Record<string, string> = { INSTITUTIONAL_APPROVAL_REQUIRED: 'Cần phê duyệt thể chế', OPERATOR_CONSENT_REQUIRED: 'Cần xác nhận đồng ý', RETENTION_DECISION_REQUIRED: 'Cần quyết định lưu giữ', RETENTION_AUTHORITY_UNVERIFIED: 'Chưa xác minh thẩm quyền lưu giữ', STORAGE_ENCRYPTION_UNVERIFIED: 'Chưa xác minh mã hóa vùng lưu trữ', STORAGE_ACL_UNVERIFIED: 'Chưa xác minh quyền truy cập vùng lưu trữ', RESEARCH_COLLECTION_NOT_IMPLEMENTED: 'Thu thập nghiên cứu chưa được triển khai' };
const savedResearchSessionId = /^research-[A-Za-z0-9_-]{16,128}$/;
type Scope = 'study' | 'participant' | 'session' | 'consent' | 'readiness' | 'recovery' | 'withdrawal';
type ActionError = { scope: Scope; message: string } | undefined;

const lifecycleLabels: Record<ResearchSession['state'], string> = {
  DRAFT: 'Bản nháp',
  CONSENT_CONFIRMED: 'Đã xác nhận đồng ý',
  PREFLIGHT_READY: 'Đã sẵn sàng kiểm tra trước',
  RECORDING: 'Đang ghi nhận',
  SEALED: 'Đã niêm phong',
  FAILED: 'Lỗi kỹ thuật',
  WITHDRAWN: 'Đã rút',
};

function Notice({ error, scope, retry, label }: { error: ActionError; scope: Scope; retry?: () => void; label: string }) {
  if (error?.scope !== scope) return null;
  return <div className="researchError" role="alert" aria-live="assertive"><p>{error.message}</p>{retry && <button className="linkButton" onClick={retry}>{label}</button>}</div>;
}

function ResearchPreparationCore({ api }: { api: ResearchApi }) {
  const [studyCode, setStudyCode] = useState(''); const [study, setStudy] = useState<ResearchStudy>(); const [participant, setParticipant] = useState<ResearchParticipant>(); const [session, setSession] = useState<ResearchSession>(); const [policy, setPolicy] = useState(''); const [endDate, setEndDate] = useState(''); const [receipt, setReceipt] = useState(''); const [version, setVersion] = useState(''); const [ready, setReady] = useState<ResearchReadiness>(); const [recovery, setRecovery] = useState<ResearchRecovery>(); const [withdrawal, setWithdrawal] = useState<WithdrawalStatus>(); const [savedSessionId, setSavedSessionId] = useState(''); const [recoveryNotice, setRecoveryNotice] = useState(''); const [confirmOpen, setConfirmOpen] = useState(false); const [pending, setPending] = useState<Scope>(); const [error, setError] = useState<ActionError>(); const [unavailable, setUnavailable] = useState(false);
  const keys = useRef(new Map<Scope, string>()); const unavailableRef = useRef<HTMLHeadingElement>(null); const savedSessionInput = useRef<HTMLInputElement>(null); const recoveryNoticeRef = useRef<HTMLParagraphElement>(null); const withdrawalTrigger = useRef<HTMLButtonElement>(null); const withdrawalCancel = useRef<HTMLButtonElement>(null); const withdrawalConfirm = useRef<HTMLButtonElement>(null); const terminal = withdrawal?.terminal === true || recovery?.state === 'WITHDRAWN' || session?.state === 'WITHDRAWN';
  useEffect(() => { if (unavailable) unavailableRef.current?.focus(); }, [unavailable]);
  useEffect(() => { savedSessionInput.current?.focus(); }, []);
  useEffect(() => { if (recoveryNotice) recoveryNoticeRef.current?.focus(); }, [recoveryNotice]);
  useEffect(() => { if (!confirmOpen) return; const timer = window.setTimeout(() => withdrawalCancel.current?.focus(), 0); return () => window.clearTimeout(timer); }, [confirmOpen]);
  const key = (scope: Scope) => { const prior = keys.current.get(scope); if (prior) return prior; const next = newIdempotencyKey(); keys.current.set(scope, next); return next; };
  const message = (scope: Scope, action: string, cause: unknown) => cause instanceof ApiError && cause.status === 404 ? `${scope === 'study' ? 'bản nháp nghiên cứu' : `tài nguyên ${scope}`} không còn tồn tại hoặc đã cũ.` : cause instanceof ApiError && cause.status === 409 ? `${action}: yêu cầu xung đột; giữ nguyên mã idempotency để đối soát.` : cause instanceof ApiError && cause.status === 401 ? 'Phiên người đánh giá đã hết hạn. Vui lòng xác thực lại.' : `${action}. Vui lòng thử lại.`;
  const fail = (scope: Scope, action: string, cause: unknown) => { if (scope === 'study' && isMissingResearchRoute(cause)) setUnavailable(true); else setError({ scope, message: message(scope, action, cause) }); };
  const write = async <T,>(scope: Scope, action: string, work: (idempotencyKey: string) => Promise<T>, success: (value: T) => void) => { setPending(scope); setError(undefined); try { const value = await work(key(scope)); keys.current.delete(scope); success(value); } catch (cause) { fail(scope, action, cause); } finally { setPending(undefined); } };
  const loadRecovery = async (id = session?.id) => { if (!id) return; setPending('recovery'); setError(undefined); try { setRecovery(await api.getRecovery(id)); } catch (cause) { fail('recovery', 'Không thể tải trạng thái khôi phục', cause); } finally { setPending(undefined); } };
  const loadReadiness = async () => { if (!session) return; setPending('readiness'); setError(undefined); try { setReady(await api.readiness(session.id)); } catch (cause) { fail('readiness', 'Không thể tải cổng sẵn sàng', cause); } finally { setPending(undefined); } };
  const restore = async () => {
    const id = savedSessionId.trim();
    if (!savedResearchSessionId.test(id)) { setError({ scope: 'recovery', message: 'Mã phiên nghiên cứu đã lưu không hợp lệ.' }); return; }
    setPending('recovery'); setError(undefined); setRecoveryNotice('Đang khôi phục phiên nghiên cứu đã lưu.');
    try {
      const restored = await api.getRecovery(id);
      if (restored.sessionId !== id) throw new Error('Research recovery response is invalid');
      const restoredReadiness = await api.readiness(id);
      const restoredWithdrawal = restored.state === 'WITHDRAWN' ? await api.withdrawalStatus(id) : undefined;
      if (restored.state === 'WITHDRAWN' && restoredWithdrawal?.terminal !== true) throw new Error('Research withdrawal response is invalid');
      setSession({ id: restored.sessionId, state: restored.state }); setRecovery(restored); setReady(restoredReadiness); setWithdrawal(restoredWithdrawal); setRecoveryNotice('Đã khôi phục phiên nghiên cứu đã lưu.');
    } catch (cause) { setRecoveryNotice(''); fail('recovery', 'Không thể khôi phục phiên nghiên cứu đã lưu', cause); } finally { setPending(undefined); }
  };
  const createStudy = () => { if (!study && studyCode) void write('study', 'Không thể tạo bản nháp nghiên cứu', (id) => api.createStudy(studyCode, id), setStudy); };
  const createParticipant = () => { if (study && !participant) void write('participant', 'Không thể tạo mã giả danh', (id) => api.createParticipant(study.id, id), setParticipant); };
  const createSession = () => { if (!study || !participant || session) return; const retention = endDate ? parseRetentionEndDate(endDate) : { iso: null, error: null }; if (retention.error) { setError({ scope: 'session', message: retention.error }); return; } const input = { studyId: study.id, participantId: participant.id, ...(policy ? { retentionPolicyReference: policy } : {}), ...(retention.iso ? { retentionEndDate: retention.iso } : {}) }; void write('session', 'Không thể khởi tạo phiên nghiên cứu', (id) => api.createResearchSession(input, id), (value) => { setSession(value); setReady(undefined); void loadRecovery(value.id); }); };
  const consent = () => { if (session && !terminal && receipt && version) void write('consent', 'Không thể xác nhận đồng ý', (id) => api.confirmResearchConsent(session.id, { consentReceiptId: receipt, consentVersion: version }, id), setSession); };
  const closeWithdrawal = () => { setConfirmOpen(false); window.setTimeout(() => withdrawalTrigger.current?.focus(), 0); };
  const withdraw = () => { if (session && !terminal) void write('withdrawal', 'Không thể rút khỏi nghiên cứu', (id) => api.withdraw(session.id, id), (value) => { setWithdrawal(value); closeWithdrawal(); void loadRecovery(session.id); }); };
  const dialogKey = (event: React.KeyboardEvent<HTMLElement>) => { if (event.key === 'Escape') { event.preventDefault(); closeWithdrawal(); } else if (event.key === 'Tab') { event.preventDefault(); if (document.activeElement === withdrawalCancel.current) withdrawalConfirm.current?.focus(); else withdrawalCancel.current?.focus(); } };
  if (unavailable) return <section className="researchPreparation researchUnavailable" role="region" aria-labelledby="m1-unavailable"><h2 ref={unavailableRef} id="m1-unavailable" tabIndex={-1}>Chế độ M1 chưa được bật</h2><p>Backend hiện tại không cung cấp API chuẩn bị nghiên cứu. Không có dữ liệu demo, phiên giả, ghi nhận hay thu thập nào được tạo.</p></section>;
  return <section className="researchPreparation" role="region" aria-labelledby="research-preparation-heading">
    <div className="researchHeading"><div><p className="eyebrow">M1 / QUẢN TRỊ NGHIÊN CỨU</p><h2 id="research-preparation-heading" className="nfcText">Chuẩn bị nghiên cứu</h2></div><p className="researchBlocker researchStatusBanner">Chưa có phê duyệt thể chế; M1 không thể ghi nhận hoặc thu thập dữ liệu.</p></div><p className="technicalNote">Chỉ tạo mã giả danh và trạng thái quản trị. Không thiết lập phê duyệt thể chế hoặc thẩm quyền lưu giữ từ giao diện này.</p>
    <section className="researchRecovery" aria-labelledby="saved-session-heading"><h3 id="saved-session-heading">Khôi phục phiên đã lưu</h3><p className="researchStatusBanner">Nhập mã phiên đã ghi trước đó để tải trạng thái quản trị và các cổng chặn từ máy chủ.</p><label htmlFor="saved-research-session-id">Mã phiên nghiên cứu đã lưu</label><input ref={savedSessionInput} id="saved-research-session-id" value={savedSessionId} disabled={Boolean(session)} onChange={(event) => setSavedSessionId(event.target.value)} autoComplete="off" spellCheck={false} /><button className="quietButton" disabled={Boolean(session) || !savedSessionId.trim() || pending === 'recovery'} onClick={() => void restore()}>Khôi phục phiên</button><p ref={recoveryNoticeRef} role="status" aria-live="polite" tabIndex={-1}>{recoveryNotice}</p><p className="technicalNote">Ghi mã phiên này ngoài ứng dụng nếu cần khôi phục sau khi khởi động lại. Ứng dụng không tự lưu mã phiên.</p><Notice error={error} scope="recovery" retry={() => void restore()} label="Thử lại khôi phục phiên" /></section>
    <div className="researchGrid">
      <section aria-labelledby="study-heading"><h3 id="study-heading">1. Bản nháp nghiên cứu</h3><label htmlFor="study-code">Mã nghiên cứu</label><input id="study-code" value={studyCode} disabled={Boolean(study)} onChange={(event) => setStudyCode(event.target.value)} autoComplete="off" /><button className="inkButton" disabled={!studyCode || Boolean(study) || pending === 'study'} onClick={createStudy}>Tạo bản nháp nghiên cứu</button>{study && <p aria-live="polite">{study.studyCode}</p>}<Notice error={error} scope="study" retry={createStudy} label="Thử lại tạo bản nháp nghiên cứu" /></section>
      <section aria-labelledby="participant-heading"><h3 id="participant-heading">2. Người tham gia mã giả danh</h3><p>Không nhập tên, liên hệ hoặc dữ liệu định danh.</p><button className="quietButton" disabled={!study || Boolean(participant) || pending === 'participant'} onClick={createParticipant}>Tạo mã giả danh người tham gia</button>{participant && <p aria-live="polite">{participant.pseudonym}</p>}<Notice error={error} scope="participant" retry={createParticipant} label="Thử lại tạo mã giả danh" /></section>
      <section aria-labelledby="session-heading"><h3 id="session-heading">3. Phiên và lưu giữ</h3><label htmlFor="retention-policy">Tham chiếu chính sách lưu giữ</label><input id="retention-policy" value={policy} disabled={endDate !== '' || Boolean(session)} onChange={(event) => setPolicy(event.target.value)} autoComplete="off" /><label htmlFor="retention-end">Ngày kết thúc lưu giữ</label><input id="retention-end" type="text" inputMode="numeric" placeholder="dd/mm/yyyy" aria-describedby="retention-end-help" value={endDate} disabled={policy !== '' || Boolean(session)} onChange={(event) => setEndDate(event.target.value)} autoComplete="off" /><p id="retention-end-help" className="technicalNote">Nhập theo định dạng dd/mm/yyyy.</p><button className="inkButton" disabled={!study || !participant || Boolean(session) || pending === 'session'} onClick={createSession}>Khởi tạo phiên nghiên cứu</button>{session && <><p aria-live="polite">Phiên nghiên cứu: {session.id}</p>{endDate && <p aria-live="polite">Ngày kết thúc lưu giữ đã ghi: {formatRetentionEndDate(parseRetentionEndDate(endDate).iso ?? endDate)}</p>}<p className="technicalNote">Ghi mã này ngoài ứng dụng để khôi phục khi cần.</p></>}<Notice error={error} scope="session" retry={createSession} label="Thử lại khởi tạo phiên nghiên cứu" /></section>
      <section aria-labelledby="consent-heading"><h3 id="consent-heading">4. Xác nhận đồng ý của người đánh giá</h3><p>Thao tác này thuộc quản trị M1, tách biệt hoàn toàn với luồng thí sinh M0.</p><label htmlFor="consent-receipt">Mã biên nhận đồng ý</label><input id="consent-receipt" value={receipt} disabled={!session || terminal} onChange={(event) => setReceipt(event.target.value)} autoComplete="off" /><label htmlFor="consent-version">Phiên bản đồng ý</label><input id="consent-version" value={version} disabled={!session || terminal} onChange={(event) => setVersion(event.target.value)} autoComplete="off" /><button className="quietButton" disabled={!session || terminal || !receipt || !version || pending === 'consent'} onClick={consent}>Xác nhận đồng ý của người đánh giá</button><Notice error={error} scope="consent" retry={consent} label="Thử lại xác nhận đồng ý" /></section>
    </div>
    {session && <section className="researchReadiness" aria-labelledby="readiness-heading"><h3 id="readiness-heading">Cổng sẵn sàng và khôi phục</h3><button className="quietButton" disabled={pending === 'readiness'} onClick={() => void loadReadiness()}>Tải cổng sẵn sàng</button><Notice error={error} scope="readiness" retry={() => void loadReadiness()} label="Thử lại tải cổng sẵn sàng" />{ready && <div aria-live="polite"><p className={ready.ready ? 'readinessReady' : 'readinessBlocked'}>{ready.ready ? 'Sẵn sàng theo cổng máy chủ' : 'Chưa sẵn sàng cho thu thập'}</p>{!ready.ready && <p>Không thể ghi nhận hoặc thu thập khi vẫn còn cổng chặn.</p>}<ul>{ready.blockingGates.map((gate) => <li key={gate}>{gates[gate] ?? `Mã kỹ thuật chưa hỗ trợ: ${gate}`}</li>)}</ul></div>}<button className="quietButton" disabled={pending === 'recovery'} onClick={() => void loadRecovery()}>Tải trạng thái khôi phục</button><Notice error={error} scope="recovery" retry={() => void loadRecovery()} label="Thử lại tải trạng thái khôi phục" />{recovery && <div aria-live="polite"><p>Trạng thái khôi phục: {lifecycleLabels[recovery.state]}</p>{recovery.collectionBlocked && recovery.reauthenticationRequired && <p>Thu thập bị chặn; cần xác thực lại khi khôi phục.</p>}</div>}</section>}
    {session && <section className="withdrawalPanel" aria-labelledby="withdrawal-heading"><h3 id="withdrawal-heading">Rút khỏi nghiên cứu</h3>{terminal ? <div aria-live="polite"><p className="readinessBlocked">Đã rút khỏi nghiên cứu</p><p>{withdrawal?.taskCount ?? 0} tác vụ đối soát đang chờ</p><ReconciliationPanel api={api} sessionId={session.id} /></div> : confirmOpen ? <div role="alertdialog" aria-modal="true" aria-labelledby="withdrawal-title" onKeyDown={dialogKey}><h4 id="withdrawal-title">Xác nhận rút khỏi nghiên cứu</h4><p>Thao tác này áp dụng cho người tham gia này và tất cả phiên nghiên cứu liên quan của họ. Xuất và hiện vật phải được đối soát; không thể hoàn tác trong M1.</p><button ref={withdrawalCancel} className="quietButton" onClick={closeWithdrawal}>Quay lại</button><button ref={withdrawalConfirm} className="orangeButton" disabled={pending === 'withdrawal'} onClick={withdraw}>Xác nhận rút khỏi nghiên cứu</button></div> : <><p className="withdrawalWarning">Rút khỏi nghiên cứu áp dụng cho người tham gia này và tất cả phiên nghiên cứu liên quan của họ. Xuất và hiện vật phải được đối soát; không thể hoàn tác trong M1.</p><button ref={withdrawalTrigger} className="orangeButton" onClick={() => setConfirmOpen(true)}>Yêu cầu rút khỏi nghiên cứu</button></>}<Notice error={error} scope="withdrawal" retry={withdraw} label="Thử lại rút khỏi nghiên cứu" /></section>}
  </section>;
}

export function ResearchPreparation({ api }: { api: ResearchApi }) {
  return <><ResearchPreparationCore api={api} />{isSyntheticReviewApi(api) && <SyntheticValidationPanel api={api} />}</>;
}
